version: '3.8'

services:
  # Web application service / Сервіс веб-додатку
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4999:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
    volumes:
      - ./app.py:/app/app.py
      - ./templates:/app/templates
      - ./static:/app/static
    restart: unless-stopped

  # Example database service / Приклад сервісу бази даних
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=flask_user
      - POSTGRES_PASSWORD=flask_password
      - POSTGRES_DB=flask_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: 